//共性
var sound = {
  rightAudio:function(){//正确
    cc.audioEngine.playEffect(res.Right_audio);
  },
  wrongAudio:function(){//错误
    cc.audioEngine.playEffect(res.Wrong_audio);
  },
  winAudio:function(){//完成 欢呼
    cc.audioEngine.playEffect(res.Win_audio);
  },
  starAudio:function(){//飞星
    cc.audioEngine.playEffect(res.Star_audio);
  },
  buttonAudio:function(){//点击
    cc.audioEngine.playEffect(res.Button_audio);
  },
  stopAudio : function(){//停止
    cc.audioEngine.stopMusic();
  },
    stopEff:function () {//停止播放音效
        cc.audioEngine.stopAllEffects();
    },
  //个性
  gameBgAudio:function(){//背景
    cc.audioEngine.playMusic(res.GameBg_audio,true);
    cc.audioEngine.setMusicVolume(0.2);  
  },
  hintAudio:function(){//提示
    cc.audioEngine.playEffect(res.seesaw_problem);
  },
  gatherHoneyAudio:function(){//提示
      cc.audioEngine.playEffect(res.GatherHoney_audio);
  },
  dragAudio:function(){//提示
      cc.audioEngine.playEffect(res.Drag_audio);
  },
  butterAudio:function(){//提示
      cc.audioEngine.playEffect(res.Butter_audio);
  },
  fireAudio:function(){//提示
      cc.audioEngine.playEffect(res.Fire_audio);
  },
  honeyAudio:function(){//提示
      cc.audioEngine.playEffect(res.Honey_audio);
  },
  fireglowAudio:function(){//提示
      cc.audioEngine.playEffect(res.Fireglow_audio);
  },
  dragOneAudio:function(){//提示
      cc.audioEngine.playEffect(res.DragOne_audio);
  },
  dragThreeAudio:function(){//提示
      cc.audioEngine.playEffect(res.DragThree_audio);
  },
  dragFourAudio:function(){//提示
      cc.audioEngine.playEffect(res.DragFour_audio);
  },
  dragFiveAudio:function(){//提示
      cc.audioEngine.playEffect(res.DragFive_audio);
  },
  butterOneAudio:function(){//提示
      cc.audioEngine.playEffect(res.ButterOne_audio);
  },
  butterThreeAudio:function(){//提示
      cc.audioEngine.playEffect(res.ButterThree_audio);
  },
  butterFourAudio:function(){//提示
      cc.audioEngine.playEffect(res.ButterFour_audio);
  },
  butterFiveAudio:function(){//提示
      cc.audioEngine.playEffect(res.ButterFive_audio);
  },
  honeyeeAudio:function(){//提示
      cc.audioEngine.playEffect(res.Honeybee_audio);
  },

}