//公共资源
var res = {
   //个性图片配音 音效
	DragBg:"dragonfly/bj.jpg",
	DragOne:"dragonfly/one.png",
	DragTwo:"dragonfly/two.png",
	DragThree:"dragonfly/three.png",
	DragFour:"dragonfly/dragonfly_one.png",
    DragFourFlay:"dragonfly/dragonfly_two.png",
	FireOne:"firefly/-g-one.png",
	FireTwo:"firefly/-g-two.png",
	FireThree:"firefly/-g-three.png",
	FireFour:"firefly/-g-four.png",
	FireFive:"firefly/-g-five.png",
	FireSix:"firefly/-g-six.png",
	FireSeven:"firefly/-g-sevev.png",
	FireEight:"firefly/-g-eight.png",
	FireNine:"firefly/-g-nine.png",
	FireTen:"firefly/-g-ten.png",
	FireGlowOne:"firefly/-g-glowworm_one.png",
	FireGlowTwo:"firefly/-g-glowworm_two.png",
	FireGlowThree:"firefly/-g-glowworm_three.png",
	FireGlowFour:"firefly/-g-glowworm_four.png",
	FireGlowFive:"firefly/-g-glowworm_five.png",
	FireGlowSix:"firefly/-g-glowworm_six.png",
	FireGlowSeven:"firefly/-g-glowworm_seven.png",
	FireGlowEight:"firefly/-g-glowworm_eight.png",
	FireGlowNine:"firefly/-g-glowworm_night.png",
	FireGlowTen:"firefly/-g-glowworm_ten.png",
	FireBg:"firefly/-g-glowworm_bj.jpg",
	Black:"firefly/black_glowworm.png",
	ButterBg:"butterfly/-g-bg.jpg",
	ButterFly:"butterfly/-g-butterfly.png",
	ButterLeaf:"butterfly/-g-leaf.png",
    ButterFlyOne:"butterfly/butterfly_flying_one.png",
    ButterFlyTwo:"butterfly/butterfly_flying_two.png",
	EggOne:"butterfly/egg_evolution_one.png",
    EggTwo:"butterfly/egg_evolution_two.png",
    EggThree:"butterfly/egg_evolution_three.png",
    EggFour:"butterfly/egg_evolution_four.png",
	LarveOne:"butterfly/larva_evolution_one.png",
    LarveTwo:"butterfly/larva_evolution_two.png",
    LarveThree:"butterfly/larva_evolution_three.png",
    LarveFour:"butterfly/larva_evolution_four.png",
    LarveFive:"butterfly/larva_evolution_five.png",
	LarveSix:"butterfly/larva_evolution_six.png",
	LarveSeven:"butterfly/larva_evolution_seven.png",
	LarveEight:"butterfly/larva_evolution_eight.png",
    LarveNine:"butterfly/larva_evolution_night.png",
	HoneyBg:"honeybee/bg.jpg",
	HoneyHive:"honeybee/hive.png",
	HoneyReturnOne:"honeybee/returns_one.png",
	HoneyReturnTwo:"honeybee/returns_two.png",
	HoneybeeOne:"honeybee/honeybee_one.png",
	HoneybeeTwo:"honeybee/honeybee_eight.png",
	HoneyTree:"honeybee/tree.png",
	HoneyStomachOne:"honeybee/stomach_one.png",
	HoneyStomachTwo:"honeybee/stomach_two.png",
	HoneyStomachThree:"honeybee/stomach_three.png",
	HoneyStomachFour:"honeybee/return_four.png",
	HoneyOne:"honeybee/stomach_one.png",
	HoneyTwo:"honeybee/honeybee_two.png",
	HoneyThree:"honeybee/honeybee_three.png",
	HoneyFour:"honeybee/honeybee_four.png",
	HoneyFlowerOne:"honeybee/flower_one.png",
	HoneyFlowerTwo:"honeybee/flower_two.png",
	HoneyFlowerThree:"honeybee/flower_three.png",
	HoneyCloudsOne:"honeybee/white_clouds.png",
	HoneyCloudsTwo:"honeybee/white_clouds_one.png",
	HoneyCloudsThree:"honeybee/white_clouds_two.png",
	HoneyLayer:"honeybee/white_layer.png",
	HoneyWhiteOne:"honeybee/white_one.png",
	HoneyWhiteTwo:"honeybee/white_two.png",
	HoneyWhiteThree:"honeybee/white_three.png",
	HoneyFlower:"honeybee/flower.png",
	//lang
    bright: "firefly/-g-bg_bright.jpg",
    butterfly: "firefly/-g-butterfly.png",
    dragonfly: "firefly/-g-dragonfly.png",
	mifeng: "honeybee/honeybee_one.png",
    aperture: "firefly/-g-aperture.png",
	modal: "firefly/modal.jpg",
	Drag_audio:"audio/insect_four.mp3",
	Butter_audio:"audio/insect_one.mp3",
	Fire_audio:"audio/insect_three.mp3",
	Honey_audio:"audio/insect_two.mp3",
	//萤火虫声音
	Do_audio:"firefly/do.mp3",
    Fa_audio:"firefly/fa.mp3",
    La_audio:"firefly/la.mp3",
    Mi_audio:"firefly/mi.mp3",
    Ruai_audio:"firefly/ruai.mp3",
    Xi_audio:"firefly/xi.mp3",
	Fireglow_audio:"audio/glowworm.mp3",
	//蜜蜂声音
	GatherHoney_audio:"honeybee/gather_honey.mp3",
	Honeybee_audio:"audio/honeybee.mp3",
	//蜻蜓声音
	DragOne_audio:"audio/dragonfly_one.mp3",
	DragThree_audio:"audio/dragonfly_three.mp3",
	DragFour_audio:"audio/dragonfly_four.mp3",
	DragFive_audio:"audio/dragonfly_five.mp3",
	//蝴蝶声音
	ButterOne_audio:"audio/egg.mp3",
	ButterThree_audio:"audio/butterfly_two.mp3",
	ButterFour_audio:"audio/butterfly_three.mp3",
	ButterFive_audio:"audio/butterfly_four.mp3",

    //声音
    Right_audio : "common/right.mp3",
    Wrong_audio : "common/wrong.mp3",
    Win_audio : "common/celebration.mp3",
    Star_audio : "common/star.m4a",
    Button_audio : "common/button.wav",
    GameBg_audio : "common/light_song_for_kids.mp3",

    //图片
    Back : "common/back.png", //头部公共部分
    BlackStar : "common/shape.png",
    FlyStar : "common/flay-star.png",
    LightStar : "common/light-star.png",
    ResultBg : "common/result-image-bg.png",
    RepeatNormal : "common/result-btn-repeat-normal.png",
    DoneNormal : "common/result-btn-done-normal.png",
    RepeatPress : "common/result-btn-repeat-pressed.png",
    DonePress : "common/result-btn-done-pressed.png",
    Hand : "common/hand.png",
    HandClick : "common/handclick.png",
    celebrateGirl:"common/celebrate-girl.png",
};

/*预加载资源*/
var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}